choria-io/mcorpc-ruby-support

CHANGELOG.md, Rakefile, lib/mcollective.rb
=> (misc) Release 2.21.1

CHANGELOG.md, Rakefile, lib/mcollective.rb
=> (misc) Release 2.22.0

lib/mcollective/config.rb, spec/unit/mcollective/config_spec.rb
=> (#72) stop parsing registration related settings

lib/mcollective/config.rb
=> (#75) relax config parsing for server configs

lib/mcollective/util.rb
=> (#63) modernise windows prefix

CHANGELOG.md, Rakefile, lib/mcollective.rb
=> (misc) Release 2.23.0

lib/mcollective/application/choria.rb, lib/mcollective/application/federation.rb
=> (#92) further request_cert cleanups

lib/mcollective/application/ping.rb
=> (#83) restore ping as a low level test requirement

lib/mcollective/util.rb, spec/unit/mcollective/util_spec.rb
=> (#117) improve resolving user configs

CHANGELOG.md, Rakefile, lib/mcollective.rb
=> (misc) Release 2.23.2

CHANGELOG.md, Rakefile, lib/mcollective.rb
=> (misc) Release 2.23.3

lib/mcollective/pluginpackager/forge_packager.rb
=> (#127) update erb rendering flags

lib/mcollective/config.rb, spec/fixtures/config/client.conf, spec/fixtures/config/project/choria.conf, spec/fixtures/config/project/project2/choria.conf, spec/unit/mcollective/config_spec.rb
=> (#130) support project configurations

lib/mcollective/discovery/delegate.rb
=> (#133) fix choria executable name

Gemfile, lib/mcollective/discovery/broadcast.ddl, lib/mcollective/discovery/choria.ddl, lib/mcollective/discovery/external.ddl, lib/mcollective/discovery/file.ddl, lib/mcollective/discovery/flatfile.ddl, lib/mcollective/discovery/inventory.ddl, lib/mcollective/discovery/mc.ddl, lib/mcollective/optionparser.rb, spec/spec_helper.rb, spec/unit/mcollective/optionparser_spec.rb
=> (#133) add stub DDLs for choria methods, fix --nodes

CHANGELOG.md, lib/mcollective.rb, mcorpc-ruby-support.gemspec
=> (misc) Release 2.24.0

lib/mcollective/ddl.rb, lib/mcollective/generators.rb, spec/unit/mcollective/discovery/delegate_spec.rb
=> (#137) remove dataddl left overs

CHANGELOG.md, lib/mcollective.rb, mcorpc-ruby-support.gemspec
=> (misc) Release 2.24.1

Rakefile, lib/mcollective/agent/choria_util.ddl, lib/mcollective/agent/choria_util.json, lib/mcollective/agent/rpcutil.json, lib/mcollective/agent/scout.json
=> (misc) update ddls from go-choria

lib/mcollective/util.rb
This is part 1/2 to fix #146
part 2/2 is choria-io/puppet-mcollective#293
=> (#146) Fix mcollective fact on windows 1/2

CHANGELOG.md, mcorpc-ruby-support.gemspec
=> (misc) Release 2.24.3

CHANGELOG.md, mcorpc-ruby-support.gemspec
=> (misc) Release 2.24.4

lib/mcollective/discovery/delegate.rb, spec/unit/mcollective/discovery/delegate_spec.rb
=> (#164) pass path to active configuration file to choria

CHANGELOG.md, Gemfile, mcorpc-ruby-support.gemspec
=> (misc) Release 2.25.0

CHANGELOG.md
=> (misc) Release 2.26.0
